language: java
jdk:
  - openjdk11

git:
  depth: false

#addons:
#  sonarcloud:
#    organization: "kiwiproject"
#    token:
#      secure: "TODO: add token when not private"

#script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
#  - mvn -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml clean org.jacoco:jacoco-maven-plugin:prepare-agent package org.jacoco:jacoco-maven-plugin:report sonar:sonar -Dsonar.projectKey=kiwiproject_dropwizard-config-providers