language: java
jdk:
  - openjdk11

git:
  depth: false

addons:
  sonarcloud:
    organization: "kiwiproject"
    token:
      secure: "h5aI//LbEK9Q0lDfRzO2NsG2Xl9ybB7zXfUH+uTVx576ZRqBnIzDPdPXpZdiFXYWra/ax5gIfLg2Zyt+cDsPZexNd3Zm2P2OEvK1mXiB5S7InA9LLB8fUikw9nwYqdWygXlkA6H4lDdBujtXlHteQacneH5UoWHLFYp2y8nWrxzoJR6qX3wdvlJ9hUnc4a07+zKd/Ad/vyPqh+mwRtn/ZUKtC802oru9HmopVEgtUfymhsJ0ED1dnSUOeXQT0rexzSVaGqVIhe1xLp17LqoMkjIKCCRLPdfgAnmRTvyLZ/FNdQWToLOxT8WU1n0Vh0jV1vRXfuoVBdxNrHJBZh/c6Cr6zATCUediTJgmCzP8VoM/ndHvHkSW46Vzjd25T5dJU2/CFkXBYA6Xvb6tmpQIOlnJDEA1rlSXHraVYtZNqSBz6JXI/YMhf67mWoiHxroo3tpmpUC9kWkgvbv5jzrhK4Pw9A+PMkorx1+fc3D8Xq4f7/HO3yXVz0uRP+NF3EgbX81lrOFV4hwg+s9g2TtLInrkfYgr4aZtZU++EE/NcjBWPMh1iNP+Cm2HQ1NdAjF5P875V7kdESx7pYkvHNpQfblOLtLQP0nlX/Jtr+ynaU17natf0V08hFa6fSGllTGE2vC4yOuOnuzEB8eWutrUD1My+FTt+V4m9BtyHKIF638="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml clean org.jacoco:jacoco-maven-plugin:prepare-agent package org.jacoco:jacoco-maven-plugin:report sonar:sonar -Dsonar.projectKey=kiwiproject_dropwizard-config-providers